### ISSUE TITLE
Using interceptor causes test to fail on Appium-specific command.

### ISSUE THREAD

**Issue by heavy-razzer** [enriquegh/java-selenium-http-logging#1]
Code example on Kotlin:

Set up driver:
```
val factory = HTTPFactory()
val executor = HttpCommandExecutor(emptyMap(), URL(url), factory)
val driver = IOSDriver<MobileElement>(executor, capabilities)
```

Perform tap on the element
```
val element: MobileElement
val tapOptions = TapOptions().withElement(ElementOption.element(element))
PlatformTouchAction(driver as AppiumDriver<*>).tap(tapOptions).perform()
```

Program will crash on the 3rd line with
**org.openqa.selenium.UnsupportedCommandException: performTouchAction**

**Note:**
okhttp, logging-interceptor - version 4.9.3
Appium java-client - 7.6.0

**Comment by enriquegh** [comment]
hey @heavy-razzer is `PlatformTouchAction` a custom class? I don't see this on the appium-client bindings.
I'm assuming it wraps `TouchAction` class?

If so, can you try changing:
```
HttpCommandExecutor executor = new HttpCommandExecutor(Collections.emptyMap(), new URL(SAUCE_URL), factory);
```
to:
```
AppiumCommandExecutor executor = new AppiumCommandExecutor(MobileCommand.commandRepository, new URL(SAUCE_URL), factory);
```
I'd write it in Kotlin but I don't have an easy way to test it.

This should tell the executor to add the `additionalCommands` parameter that handles custom Appium commands.

Let me know if this helps and I'll change it in the repo.

**Comment by heavy-razzer** [comment]
Thanks you for the response!

Yep, i was referring to `TouchAction` class from `io.appium.java_client` package

I changed code to 
`val executor = AppiumCommandExecutor(MobileCommand.commandRepository, URL(url), factory)`
and now all is working correct.
